site_name: Art Tools by Dmitry Gubkin
repo_url: https://github.com/DmitryGubkin/ArtToolsDoc
repo_name: 'GitHub'
edit_uri: tree/master/docs/
theme:
  name: material
  scheme: slate
  palette: 
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode