site_name: Art Tools by Dmitry Gubkin
plugins:
  - search # necessary for search to work
  - awesome-pages
theme:
  name: material
  scheme: slate
  palette: 
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode