site_name: My Docs
theme:
  name: material
  scheme: slate
  palette: 
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode