site_name: Art Tools by Dmitry Gubkin
site_url: http://DmitryGubkin.github.io/DG_ArtToolsDoc
# repo_name: DG_ArtToolsDoc
# repo_url: https://github.com/DmitryGubkin/DG_ArtToolsDoc
# edit_uri: ""

### MD Ext ###
markdown_extensions:
  - meta
  - tables
  - attr_list
  - abbr
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
### MD Ext End ###

### CSS ###
extra_css:
  - stylesheets/extra.css
### CSS End ###

### Plugins ###
plugins:
  - search # necessary for search to work
  - awesome-pages
  - mkdocs-video
### Plugins End ###

### Theme ###
theme:
  name: material
  custom_dir: overrides
  scheme: slate # set default mode
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
  palette:
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
### Theme End ###

### Footer ###
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dmitry-gubkin-3d/
    - icon: fontawesome/brands/artstation
      link: https://www.artstation.com/dmitry_g
    - icon: brands/gumroad
      link: https://dmitry-gubkin.gumroad.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/DmitryGubkinGhostStudio/videos
copyright: Copyright © 2022, Dmitry Gubkin. All rights reserved.
### Footer End ###

### Navigation ###
nav:
  - Home: index.md
  - 3ds Max:
      - Orient to World:
        - '3dsMax/orientToWorld/index.md'
        - License: '3dsMax/orientToWorld/license.md'

### Navigation End ###

    