site_name: Art Tools by Dmitry Gubkin
site_url: http://DmitryGubkin.github.io/DG_ArtToolsDoc
repo_name: DG_ArtToolsDoc
repo_url: https://github.com/DmitryGubkin/DG_ArtToolsDoc
edit_uri: ""

plugins:
  - search # necessary for search to work
  - awesome-pages
theme:
  name: material
  scheme: slate # set default mode
  palette:
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    